Fix unused parameter error (option<bool>::assign)
In file included from clipper\tests\predicate_test.cpp:2:
clipper/include/clipper.hpp: In member function 'virtual void CLI::option<bool>::assign(std::string_view)':
clipper/include/clipper.hpp:472:45: error: unused parameter 'val' [-Werror=unused-parameter]
':
clipper/include/clipper.hpp:481:48: error: unused parameter 'val' [-Werror=unused-parameter]
  481 |         inline void operator=(std::string_view val) override {
      |